#!/usr/bin/env bash
set -euo pipefail

SCRIPT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MAIN_ROOT="$(cd "$SCRIPT_ROOT/.." && pwd)/urban-city-generation"
RUN="${SPATIAL_ANCHOR_RUN:-$MAIN_ROOT/runs/spatial-anchor-smoke-v4}"
TEST_GENERATIONS="${SPATIAL_ANCHOR_TEST_GENERATIONS:-$RUN/generations-test}"
TRAIN_GENERATIONS="${SPATIAL_ANCHOR_TRAIN_GENERATIONS:-$RUN/generations-train}"
TEST_ZIP="${SPATIAL_ANCHOR_TEST_ZIP:-$MAIN_ROOT/spatial-anchor-smoke-v4-test.zip}"
TRAIN_ZIP="${SPATIAL_ANCHOR_TRAIN_ZIP:-$MAIN_ROOT/spatial-anchor-smoke-v4-train.zip}"

export CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0}"

NUM_GPUS=1 MAXIMUM_SAMPLES="${MAXIMUM_SAMPLES:-64}" BATCH_SIZE="${BATCH_SIZE:-1}" EPOCHS="${EPOCHS:-20}" SAVE_EVERY="${SAVE_EVERY:-5}" SPATIAL_ANCHOR_RUN="$RUN" bash "$SCRIPT_ROOT/scripts/run_spatial_anchor_train.sh"

SPATIAL_ANCHOR_CHECKPOINT="$RUN/best.pt" SPATIAL_ANCHOR_GENERATIONS="$TRAIN_GENERATIONS" SPATIAL_ANCHOR_GENERATION_ZIP="$TRAIN_ZIP" SPLIT=train DROP_CONTROLS=1 SAMPLES="${SAMPLES:-6}" SEEDS="${SEEDS:-3}" TEMPERATURE="${TEMPERATURE:-1.0}" bash "$SCRIPT_ROOT/scripts/run_spatial_anchor_generate.sh"

SPATIAL_ANCHOR_CHECKPOINT="$RUN/best.pt" SPATIAL_ANCHOR_GENERATIONS="$TEST_GENERATIONS" SPATIAL_ANCHOR_GENERATION_ZIP="$TEST_ZIP" SPLIT=test DROP_CONTROLS=1 SAMPLES="${SAMPLES:-6}" SEEDS="${SEEDS:-3}" TEMPERATURE="${TEMPERATURE:-1.0}" bash "$SCRIPT_ROOT/scripts/run_spatial_anchor_generate.sh"

ls -lh "$TRAIN_ZIP" "$TEST_ZIP"
